version: 2.1

orbs:
  python: circleci/python@1.5.0

executors:
  docker-publisher:
    environment:
      IMAGE_TAG: celiatois/lettings:latest
    docker:
      - image: docker:stable

jobs:
  build-and-test:
    docker:
      - image: cimg/python:3.10.2
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pip
      - run:
          name: Run tests
          command: pytest
      - run:
          name: Lint
          command: flake8

  build:
    executor: docker-publisher
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build Docker image
          command: docker build -t "${IMAGE_TAG}" .
      - run:
          name: Archive Docker image
          command: docker save --output image.tar "${IMAGE_TAG}"
      - persist_to_workspace:
          root: .
          paths:
            - ./image.tar

workflows:
  sample:
    jobs:
      - build-and-test
      - build
