version: 2.1

orbs:
  python: circleci/python@1.5.0
  heroku: circleci/heroku@2.0

jobs:
  lint-and-test:
    docker:
      - image: cimg/python:3.10.2
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pip
      - run:
          name: Run tests
          command: pytest
      - run:
          name: Lint
          command: flake8

  build-and-push:
    docker:
      - image: docker:stable
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build Docker image
          command: docker build -t $IMAGE_TAG:$CIRCLE_SHA1 .
      - run:
          name: Publish Docker image
          command: |
            echo $DOCKERHUB_PASS | docker login --username $DOCKERHUB_USERNAME --password-stdin
            docker push $IMAGE_TAG:$CIRCLE_SHA1

  deploy-to-heroku:
    docker:
      - image: cimg/python:3.10.2
    steps:
      - checkout
      - heroku/install
      - run:
          name: Deploy Main to Heroku
          command: |
            heroku container:login
            docker tag $CIRCLE_TAG registry.heroku.com/celiats-python-oc-lettings-13/web
            docker push registry.heroku.com/celiats-python-oc-lettings-13/web
            heroku container:release web

workflows:
  sample:
    jobs:
      - lint-and-test
      - build-and-push:
          context:
            - lettings
          requires:
            - lint-and-test
      - deploy-to-heroku:
          context:
            - lettings
          requires:
            - build-and-push
          filters:
            branches:
              only: main
