version: 2.1

orbs:
  python: circleci/python@1.5.0

executors:
  docker-publisher:
    environment:
      IMAGE_TAG: celiatois/lettings:latest
    docker:
      - image: docker:stable

jobs:
  build-and-test:
    docker:
      - image: cimg/python:3.10.2
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pip
      - run:
          name: Run tests
          command: pytest
      - run:
          name: Lint
          command: flake8

  build:
    executor: docker-publisher
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build Docker image
          command: docker build -t "${IMAGE_TAG}" .
      - run:
          name: Archive Docker image
          command: docker save --output image.tar "${IMAGE_TAG}"
      - persist_to_workspace:
          root: .
          paths:
            - ./image.tar

  push:
    executor: docker-publisher
    steps:
      - setup_remote_docker
      - attach_workspace:
          at: /tmp/workspace
      - run:
          name: Load Docker image
          command: docker load --input /tmp/workspace/image.tar
      - run:
          name: Publish Docker image
          command: |
            echo $DOCKERHUB_PASS | docker login --username $DOCKERHUB_USERNAME --password-stdin
            docker push "${IMAGE_TAG}"

workflows:
  sample:
    jobs:
      - build-and-test
      - build:
          requires:
            - build-and-test
      - push:
          context:
            - lettings
          requires:
            - build
