# Generated by Django 3.0 on 2023-02-20 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oc_lettings_site', '0001_initial'),
    ]

    database_operations = [
        migrations.AlterModelTable('Address', 'lettings_address'),
        migrations.AlterModelTable('Letting', 'lettings_letting'),
    ]

    state_operations = [
        migrations.DeleteModel('Address'),
        migrations.DeleteModel('Letting'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=database_operations,
            state_operations=state_operations
        )
    ]
